"""Report generator for creating markdown analysis reports."""

from datetime import datetime
from models import Report


class ReportGenerator:
    """Generate markdown reports from analysis results."""
    
    def generate_markdown(self, report: Report) -> str:
        """
        Generate markdown report.
        
        Args:
            report: Report object with analysis results
            
        Returns:
            Formatted markdown string
        """
        md = f"""# Error Analysis Report

**Generated**: {report.generated_at.strftime('%Y-%m-%d %H:%M:%S')}  
**Repository**: `{report.repository}`

---

## 📋 Error Summary

- **Type**: `{report.error_type}`
- **Message**: {report.error_message}

---

## 📍 Location

- **File**: `{report.analysis.file_path}`
- **Line**: {report.analysis.line_number}
{f"- **Function**: `{report.analysis.function_name}`" if report.analysis.function_name else ""}

---

## 💻 Code Snippet

```python
{report.analysis.code_snippet}
```

---

## 🔍 Root Cause

{report.analysis.root_cause}

---

## ✅ Recommendation

{report.analysis.recommendation}

---

## 📊 Analysis Metadata

- **Confidence**: {report.analysis.confidence:.0%} {self._get_confidence_emoji(report.analysis.confidence)}
- **Analysis Date**: {report.generated_at.strftime('%Y-%m-%d %H:%M:%S')}

---

## 📝 Original Error Log

```
{report.raw_error_log}
```

---

*Generated by Error Log Analyzer Agent*
"""
        return md
    
    def _get_confidence_emoji(self, confidence: float) -> str:
        """Get emoji based on confidence level."""
        if confidence >= 0.9:
            return "🟢"
        elif confidence >= 0.7:
            return "🟡"
        else:
            return "🔴"
    
    def save_to_file(self, report: Report, output_path: str):
        """
        Save report to markdown file.
        
        Args:
            report: Report object
            output_path: Path to output file
        """
        markdown = self.generate_markdown(report)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        print(f"✅ Report saved to: {output_path}")

